//------------------------------------------------------------------------------
// TrackRoamerMotorTypes.cs
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace TrackRoamer.Robotics.Services.TrackRoamerServices.Motor
{
    /// <summary>
    /// TrackRoamerMotor Contract
    /// </summary>
    public static class Contract
    {
        /// The Unique Contract Identifier for the TrackRoamerMotor service
		public const String Identifier = "http://schemas.trackroamer.com/robotics/2009/04/trackroamermotor.html";
    }
}
