//------------------------------------------------------------------------------
// TrackRoamerBumperTypes.cs
//
//     This code was generated by the DssNewService tool.
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace TrackRoamer.Robotics.Services.TrackRoamerServices.Bumper
{
    public static class Contract
    {
		public const string Identifier = "http://schemas.trackroamer.com/robotics/2009/04/trackroamerbumper.html";
    }
}
